apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v2
  labels:
    app: springboot
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
      version: v2
  template:
    metadata:
      labels:
        app: springboot
        version: v2
    spec:
      containers:
      - name: app
        image: gcr.io/google-samples/hello-app:2.0
        ports:
        - containerPort: 8080
